default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tenant_costs_development
  user: postgres
  host: localhost
  port: 5435

test:
  <<: *default
  database: tenant_costs_test
  user: postgres
  host: localhost
  port: 5435

production:
  <<: *default
  database: tenant_costs_production
  username: tenant_costs
  password: <%= ENV['TENANT_COSTS_DATABASE_PASSWORD'] %>
